apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kvftd02pa-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-233b16223a.5zel.p3.openshiftapps.com/rhtap/rhtap-qe:7d972d6d3e3a618e3fb44016a0d64eb457afb672@sha256:039ccfd941dc5ef0715a76e1ac7ad498c60bfdfc1bb51aa783dc1c77dc234e86
          name: container-image
